- name: Configure namenode and start hadoop
  hosts: hostnode
  tasks: 
  - name: generate worker file
    ansible.builtin.template:
      src: files/workers.j2
      dest: hadoop-3.4.0/etc/hadoop/workers
  - name: Check if HDFS is formatted
    ansible.builtin.stat:
      path: /opt/hadoop_tmp/hdfs/namenode/current/VERSION
    register: hdfs_version
  - name: Format HDFS namenode
    ansible.builtin.shell: hdfs namenode -format
    when: not hdfs_version.stat.exists
  - name: restart dfs and yarn
    ansible.builtin.shell: |
      nohup /home/almalinux/hadoop-3.4.0/sbin/stop-all.sh
      nohup /home/almalinux/hadoop-3.4.0/sbin/start-all.sh
